# Numpy


In the first section we defined Python as a great general-purpose programming language on its own, but with the help of other popular libraries as(numpy, scipy, matplotlib, pandas etc) it becomes a powerful environment for scientific computing.

NumPy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with arrays.

In [2]:
# How to import numpy
import numpy as np
# How to check the version of the numpy package
print('numpy:', np.__version__)
# Checking the available methods
print(dir(np))

numpy: 2.0.2
['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_

## numpy array


In [3]:
# Creating python List
python_list = [1,2,3,4,5]

# Checking data types
print('Type:', type (python_list)) 
print(python_list) 

two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]

print(two_dimensional_list)

# Creating Numpy(Numerical Python) array from python list

numpy_array_from_list = np.array(python_list)

print(type (numpy_array_from_list))   
print(numpy_array_from_list) 

Type: <class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'numpy.ndarray'>
[1 2 3 4 5]


## Multidimensional array
A numpy array may have one or multiple rows and columns

In [4]:
two_dimensional = [[0,1,2], [3,4,5], [6,7,8]]
numpy_two_dimensional = np.array(two_dimensional)
print(type (numpy_two_dimensional))
print(numpy_two_dimensional)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Converting array to list

In [5]:
# We can always convert an array back to a python list using tolist().
np_to_list = numpy_array_from_list.tolist()

print('one dimensional array:', np_to_list)
print('two dimensional array: ', numpy_two_dimensional.tolist())

print(type (np_to_list))

one dimensional array: [1, 2, 3, 4, 5]
two dimensional array:  [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'list'>


## initialize arrays

In [6]:
zeros = np.zeros((5,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
ones = np.ones(((5,5)))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])

In [ ]:
print(a.dtype) # Data types of array elements
print(type(a)) # Data type of the array itself


int64
<class 'numpy.ndarray'>
(5,)


In [14]:
print(b.dtype) # Data types of array elements
print(type(b)) # Data type of the array itself
print(b.shape) # Shape of the array

int64
<class 'numpy.ndarray'>
(3, 6)


## Attributes Array

In [ ]:
print(a.shape) # Shape of the array
print(len(a)) # give us number element in array
print(a.ndim) # give us the dimentions

(5,)
5
1


In [18]:
print(b.shape) # Shape of the array
print(len(b)) # give us number element in array
print(b.ndim) # give us the dimentions

(3, 6)
3
2
